import streamlit as st
import pandas as pd
import sqlite3
from pathlib import Path
import numpy as np


# =========================================================
# DATA SENTINEL DASHBOARD
# =========================================================

st.set_page_config(
    page_title="DataSentinel",
    page_icon="🛡️",
    layout="wide"
)


# =========================================================
# PROJECT PATHS
# =========================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATABASE_PATH = PROJECT_ROOT / "database" / "datasentinel.db"
DATA_PATH = PROJECT_ROOT / "data" / "processed"


# =========================================================
# DATABASE CONNECTION
# =========================================================

def get_database_connection():
    return sqlite3.connect(DATABASE_PATH)


# =========================================================
# LOAD QUALITY REPORTS
# =========================================================

def load_quality_reports():

    conn = get_database_connection()

    try:
        df = pd.read_sql_query(
            """
            SELECT *
            FROM quality_reports
            ORDER BY report_id DESC
            """,
            conn
        )
    except Exception:
        try:
            df = pd.read_sql_query(
                """
                SELECT *
                FROM quality_reports
                ORDER BY id DESC
                """,
                conn
            )
        except Exception:
            df = pd.DataFrame()

    conn.close()

    return df


# =========================================================
# LOAD DATASET
# =========================================================

def load_dataset(filename):

    file_path = DATA_PATH / filename

    if file_path.exists():
        try:
            return pd.read_csv(file_path)
        except Exception:
            return pd.DataFrame()

    return pd.DataFrame()


# =========================================================
# STATUS HELPERS
# =========================================================

def status_icon(status):

    if status == "HEALTHY":
        return "🟢"

    if status == "WARNING":
        return "🟡"

    if status == "CRITICAL":
        return "🔴"

    return "⚪"


def get_status(value, warning_threshold, critical_threshold):

    if value <= critical_threshold:
        return "CRITICAL"

    if value <= warning_threshold:
        return "WARNING"

    return "HEALTHY"


def get_completeness_score(df):

    if df.empty:
        return 0.0

    total_cells = df.shape[0] * df.shape[1]

    if total_cells == 0:
        return 0.0

    missing_cells = int(df.isnull().sum().sum())

    return round(
        (1 - missing_cells / total_cells) * 100,
        2
    )


def get_duplicate_rate(df):

    if df.empty:
        return 0.0

    duplicate_rows = int(df.duplicated().sum())

    return round(
        (duplicate_rows / len(df)) * 100,
        2
    )


# =========================================================
# SCHEMA VALIDATION
# =========================================================

def validate_schema(df, filename):

    # Expected customer schema generated by DataSentinel
    expected_columns = [
        "customer_id",
        "name",
        "email",
        "city",
        "state",
        "signup_date",
        "age"
    ]

    # Only validate the customer datasets against
    # the known customer schema.
    if "customer" not in filename.lower():
        return {
            "status": "N/A",
            "missing": [],
            "unexpected": []
        }

    actual_columns = list(df.columns)

    missing_columns = [
        column
        for column in expected_columns
        if column not in actual_columns
    ]

    unexpected_columns = [
        column
        for column in actual_columns
        if column not in expected_columns
    ]

    if missing_columns:
        status = "CRITICAL"

    elif unexpected_columns:
        status = "WARNING"

    else:
        status = "HEALTHY"

    return {
        "status": status,
        "missing": missing_columns,
        "unexpected": unexpected_columns
    }


# =========================================================
# ANOMALY DETECTION
# =========================================================

def calculate_anomaly_rate(df):

    if df.empty:
        return 0.0

    numeric_columns = df.select_dtypes(
        include=np.number
    ).columns.tolist()

    if not numeric_columns:
        return 0.0

    anomaly_indices = set()

    # IQR-based anomaly detection
    for column in numeric_columns:

        series = df[column].dropna()

        if len(series) < 10:
            continue

        q1 = series.quantile(0.25)
        q3 = series.quantile(0.75)

        iqr = q3 - q1

        if iqr == 0:
            continue

        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr

        anomalies = df[
            (df[column] < lower_bound) |
            (df[column] > upper_bound)
        ]

        anomaly_indices.update(
            anomalies.index.tolist()
        )

    anomaly_count = len(anomaly_indices)

    return round(
        (anomaly_count / len(df)) * 100,
        2
    )


# =========================================================
# OVERALL QUALITY SCORE
# =========================================================

def calculate_quality_score(
    completeness,
    duplicate_rate,
    schema_status,
    anomaly_rate
):

    completeness_score = completeness

    duplicate_score = max(
        0,
        100 - duplicate_rate * 10
    )

    anomaly_score = max(
        0,
        100 - anomaly_rate * 10
    )

    if schema_status == "CRITICAL":
        schema_score = 0

    elif schema_status == "WARNING":
        schema_score = 50

    elif schema_status == "HEALTHY":
        schema_score = 100

    else:
        schema_score = 100

    score = (
        completeness_score * 0.35
        + duplicate_score * 0.25
        + schema_score * 0.20
        + anomaly_score * 0.20
    )

    return round(score, 2)


def overall_status(
    completeness,
    duplicate_rate,
    schema_status,
    anomaly_rate
):

    if schema_status == "CRITICAL":
        return "CRITICAL"

    if completeness < 95:
        return "CRITICAL"

    if duplicate_rate >= 5:
        return "CRITICAL"

    if anomaly_rate >= 5:
        return "CRITICAL"

    if completeness < 99:
        return "WARNING"

    if duplicate_rate > 0:
        return "WARNING"

    if anomaly_rate > 0:
        return "WARNING"

    if schema_status == "WARNING":
        return "WARNING"

    return "HEALTHY"


# =========================================================
# TITLE
# =========================================================

st.title("🛡️ DataSentinel")

st.subheader(
    "Data Quality & Anomaly Detection Platform"
)

st.write(
    """
    DataSentinel monitors datasets for common data-quality problems,
    including missing values, duplicate records, schema violations,
    and behavioral anomalies.
    """
)


# =========================================================
# REFRESH BUTTON
# =========================================================

col_refresh, col_space = st.columns([1, 5])

with col_refresh:

    if st.button(
        "🔄 Refresh Dashboard",
        use_container_width=True
    ):
        st.rerun()


st.divider()


# =========================================================
# LOAD REPORTS
# =========================================================

reports = load_quality_reports()


# =========================================================
# TOP METRICS
# =========================================================

if not reports.empty:

    latest = reports.iloc[0]

    report_id = latest.get(
        "report_id",
        latest.get("id", "N/A")
    )

    overall = latest.get(
        "overall_status",
        "N/A"
    )

    report_date = latest.get(
        "created_at",
        "N/A"
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.metric(
            "Reports Generated",
            len(reports)
        )

    with col2:

        st.metric(
            "Latest Report",
            report_id
        )

    with col3:

        st.metric(
            "Overall Status",
            f"{status_icon(overall)} {overall}"
        )

    with col4:

        st.metric(
            "Report Date",
            report_date
        )

else:

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Reports Generated", "0")

    with col2:
        st.metric("Latest Report", "N/A")

    with col3:
        st.metric("Overall Status", "N/A")

    with col4:
        st.metric("Report Date", "N/A")


# =========================================================
# QUALITY REPORT HISTORY
# =========================================================

st.divider()

st.header("📊 Data Quality Overview")


if not reports.empty:

    st.success(
        f"{len(reports)} quality report(s) found in the database."
    )

    display_reports = reports.copy()

    if "overall_status" in display_reports.columns:

        display_reports["overall_status"] = (
            display_reports["overall_status"]
            .apply(
                lambda x:
                f"{status_icon(x)} {x}"
            )
        )

    st.dataframe(
        display_reports,
        use_container_width=True,
        hide_index=True
    )

else:

    st.info(
        "No quality reports found in the database."
    )


# =========================================================
# DATASET SELECTION
# =========================================================

st.divider()

st.header("🔍 Dataset Analysis")


available_files = [
    "customers_corrupted.csv",
    "customers_duplicates.csv",
    "customers_schema_broken.csv",
    "customers_anomalies.csv",
    "customer_features.csv"
]


# Only show files that actually exist
existing_files = [
    filename
    for filename in available_files
    if (DATA_PATH / filename).exists()
]


if not existing_files:

    st.error(
        "No processed datasets were found."
    )

    st.stop()


selected_file = st.selectbox(
    "Select a dataset",
    existing_files
)


df = load_dataset(selected_file)


# =========================================================
# DATASET BASIC METRICS
# =========================================================

if not df.empty:

    completeness = get_completeness_score(df)

    duplicate_rate = get_duplicate_rate(df)

    duplicate_count = int(
        df.duplicated().sum()
    )

    schema_result = validate_schema(
        df,
        selected_file
    )

    schema_status = schema_result["status"]

    anomaly_rate = calculate_anomaly_rate(df)

    quality_score = calculate_quality_score(
        completeness,
        duplicate_rate,
        schema_status,
        anomaly_rate
    )

    final_status = overall_status(
        completeness,
        duplicate_rate,
        schema_status,
        anomaly_rate
    )

    # -----------------------------------------------------
    # DATASET HEADER
    # -----------------------------------------------------

    st.subheader(
        f"Dataset: `{selected_file}`"
    )

    # -----------------------------------------------------
    # QUALITY SCORE
    # -----------------------------------------------------

    score_col1, score_col2 = st.columns(
        [1, 2]
    )

    with score_col1:

        st.metric(
            "Overall Quality Score",
            f"{quality_score}/100"
        )

    with score_col2:

        st.metric(
            "Overall Status",
            f"{status_icon(final_status)} {final_status}"
        )


    # -----------------------------------------------------
    # QUALITY METRICS
    # -----------------------------------------------------

    st.subheader(
        "Quality Checks"
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.metric(
            "Completeness",
            f"{completeness:.2f}%"
        )

        if completeness >= 99:
            st.success("HEALTHY")

        elif completeness >= 95:
            st.warning("WARNING")

        else:
            st.error("CRITICAL")


    with col2:

        st.metric(
            "Duplicate Rate",
            f"{duplicate_rate:.2f}%"
        )

        if duplicate_rate == 0:
            st.success("HEALTHY")

        elif duplicate_rate < 5:
            st.warning("WARNING")

        else:
            st.error("CRITICAL")


    with col3:

        st.metric(
            "Schema",
            schema_status
        )

        if schema_status == "HEALTHY":
            st.success("VALID")

        elif schema_status == "WARNING":
            st.warning("CHECK")

        elif schema_status == "CRITICAL":
            st.error("INVALID")

        else:
            st.info("N/A")


    with col4:

        st.metric(
            "Anomaly Rate",
            f"{anomaly_rate:.2f}%"
        )

        if anomaly_rate == 0:
            st.success("HEALTHY")

        elif anomaly_rate < 5:
            st.warning("WARNING")

        else:
            st.error("CRITICAL")


    # =====================================================
    # QUALITY CHART
    # =====================================================

    st.subheader(
        "📈 Quality Metrics"
    )

    chart_data = pd.DataFrame(
        {
            "Metric": [
                "Completeness",
                "Duplicate Quality",
                "Schema Quality",
                "Anomaly Quality"
            ],
            "Score": [
                completeness,
                max(0, 100 - duplicate_rate * 10),
                (
                    100
                    if schema_status == "HEALTHY"
                    else 50
                    if schema_status == "WARNING"
                    else 0
                    if schema_status == "CRITICAL"
                    else 100
                ),
                max(0, 100 - anomaly_rate * 10)
            ]
        }
    )

    st.bar_chart(
        chart_data.set_index("Metric")
    )


    # =====================================================
    # SCHEMA DETAILS
    # =====================================================

    if schema_result["missing"]:

        st.error(
            "Missing columns: "
            + ", ".join(
                schema_result["missing"]
            )
        )

    if schema_result["unexpected"]:

        st.warning(
            "Unexpected columns: "
            + ", ".join(
                schema_result["unexpected"]
            )
        )


    # =====================================================
    # DATASET PREVIEW
    # =====================================================

    st.subheader(
        "Dataset Preview"
    )

    st.dataframe(
        df.head(100),
        use_container_width=True,
        hide_index=True
    )


    # =====================================================
    # MISSING VALUES
    # =====================================================

    st.header(
        "🧩 Missing Value Analysis"
    )

    missing = (
        df.isnull()
        .sum()
        .reset_index()
    )

    missing.columns = [
        "Column",
        "Missing Values"
    ]

    missing = missing[
        missing["Missing Values"] > 0
    ]

    if missing.empty:

        st.success(
            "No missing values detected."
        )

    else:

        st.warning(
            f"{int(missing['Missing Values'].sum()):,} "
            "missing value(s) detected."
        )

        st.dataframe(
            missing,
            use_container_width=True,
            hide_index=True
        )


    # =====================================================
    # DUPLICATE ANALYSIS
    # =====================================================

    st.header(
        "📋 Duplicate Analysis"
    )

    if duplicate_count == 0:

        st.success(
            "No duplicate rows detected."
        )

    else:

        st.warning(
            f"{duplicate_count:,} duplicate rows detected "
            f"({duplicate_rate:.2f}%)."
        )


    # =====================================================
    # SCHEMA ANALYSIS
    # =====================================================

    st.header(
        "🧱 Schema Validation"
    )

    if schema_status == "N/A":

        st.info(
            "Schema validation is not configured "
            "for this dataset type."
        )

    elif schema_status == "HEALTHY":

        st.success(
            "Schema is valid. All expected columns are present."
        )

    elif schema_status == "WARNING":

        st.warning(
            "Schema contains unexpected columns."
        )

    else:

        st.error(
            "Schema validation failed."
        )


    # =====================================================
    # ANOMALY ANALYSIS
    # =====================================================

    st.header(
        "🚨 Anomaly Detection"
    )

    if anomaly_rate == 0:

        st.success(
            "No numerical outliers detected."
        )

    else:

        estimated_anomalies = round(
            len(df) * anomaly_rate / 100
        )

        st.warning(
            f"Approximately {estimated_anomalies:,} "
            f"anomalous row(s) detected "
            f"({anomaly_rate:.2f}%)."
        )


    # =====================================================
    # DATASET INFORMATION
    # =====================================================

    st.header(
        "📁 Dataset Information"
    )

    info = pd.DataFrame(
        {
            "Column": df.columns,
            "Data Type": [
                str(dtype)
                for dtype in df.dtypes
            ],
            "Missing Values": [
                int(value)
                for value in df.isnull().sum()
            ],
            "Unique Values": [
                int(value)
                for value in df.nunique()
            ]
        }
    )

    st.dataframe(
        info,
        use_container_width=True,
        hide_index=True
    )


else:

    st.error(
        f"{selected_file} could not be loaded."
    )


# =========================================================
# FOOTER
# =========================================================

st.divider()

st.caption(
    "DataSentinel — Data Quality Monitoring & Anomaly Detection Platform"
)